### PR TITLE
Really Fix Transition Aborted Feature

### PR DESCRIPTION
**Pull request by jherdman**
OK, this is not my day. I'm sorry about all of the releases.

### CODE REVIEW

**Comment by lolmaus** [comment]
Got a Jira ticket assigned to me, so I'm really looking forward to having this merged and released. ^_^

**Comment by jherdman** [comment]
Sorry about the delay on this, I haven't had the bandwidth lately to look into it.

I've been mulling around the idea that this isn't a problem we should fix. I haven't been able to reproduce Transition Aborted in a trivial Ember app, and I'm concerned that we're muting actual production problems.

Thoughts?

**Comment by lolmaus** [comment]
We're seeing this all over the app.

If you don't want to have them all ignored, then is there a way to ignore them manually?

**Comment by jherdman** [comment]
You should be able to extend the `onError` call back. I have an example here https://github.com/jherdman/ember-cli-trackjs#one-caveat.

I'd love a jsbin showing how to reproduce this error, or, better yet, a failing acceptance test. It'd really help to reproduce this a lot. I kind of cowboy coded this one :(

**Comment by lolmaus** [comment]
I couldn't reproduce it in `ember-cli-trackjs` dummy up too. Then I tried `throw 'blah'` in a route's `beforeModel` hook and it wasn't caught by TrackJS either. In a real app, `throw 'blah'` is intercepted by TrackJS.

**Comment by jherdman** [comment]
I wonder if the add-on is watching for errors that it shouldn't?

**Comment by lolmaus** [comment]
I wonder if TrackJS is active in the dummy app at all?

**Comment by lolmaus** [comment]
@jherdman 

> You should be able to extend the onError call back. I have an example here https://github.com/jherdman/ember-cli-trackjs#one-caveat.

I've tried it and it won't work! The `onError` callback is never executed.

**Comment by lolmaus** [comment]
I think you should just merge this.

**Comment by lolmaus** [comment]
~~I've tried it and it won't work! The `onError` callback is never executed.~~ TrackJS was disabled for the dev env. Turns out, when disabled it's still intercept errors, but it would ignore `onError`! O_O

**Comment by lolmaus** [comment]
I'm still unable to ignore the transition error manually via `onError`. Now the problem is that `payload.message` is `"[object Object]"` string.

[screenshot](http://i.imgur.com/Aem79u4.png)

**Comment by lolmaus** [comment]
Also, `"[object Object]"` is what gets reported into TrackJS SaaS which is plain terrible.

**Comment by lolmaus** [comment]
This is how our production TrackJS report looks:

[screenshot](http://i.imgur.com/r0dls5g.png)

**Comment by jzgit** [comment]
Would be great to get this merged in.  I will look into recreating the issue in jsbin

**Comment by lolmaus** [comment]
I tried TrackJS in a clean Ember CLI app, and I'm not able to have it report errors. Only manual `.track()`s are reported. :astonished:

**Comment by jherdman** [comment]
@lolmaus can you clarify? When you say "I tried TrackJS in a clean Ember CLI app" are you talking about this add-on?

**Comment by lolmaus** [comment]
@jherdman No, I mean I did `ember new foo` and installed `ember-cli-trackjs` into it, and it only would report manual `.track()` into its backend, ignoring errors. I struggled to find out what I did wrong but failed.

And this addon's dummy app would also ignore errors.

**Comment by jherdman** [comment]
Would you be able to provide the dummy app for me? I'll try to budget some time to look into the issue in the next few days. I'm a little snowed under at work right now.

In the mean time, I welcome any pull requests. I promise to do my best to get to the ASAP. I really appreciate everyone's feedback and involvement so far :heart_eyes:

**Comment by lolmaus** [comment]
@jherdman I know that TrackJS API key isn't private, but it's not something one should expose either. So I created a private repo: https://github.com/firecracker/ember-cli-trackjs-transition-problem

@jzgit Can you please give @jherdman access to the `development-exam-sim` app reports?

**Comment by jherdman** [comment]
@lolmaus I dug in a bit, and I think we have a bonafide Ember bug on our hands. My understanding is that `Ember.onerror` should catch errors thrown in the various model hooks. One workaround is to define a handler on your application route such as:

```javascript
// app/routes/application.js

actions: {
  error(err) {
    this.get('trackjs).track(err);
  }
}
```

If anyone knows of a way to register a global route error handler I'm all ears.

**Comment by lolmaus** [comment]
So I've figured it out.

Fact 1: Ember 1.13 and Ember 2.2 behave differently. After upgrading my demo app to Ember 2.2, it started behaving identically to our commercial app.

Fact 2: Ember throws two kinds of errors: with an instance of `Error` and with a `{name, message}` plain object. TrackJS backend is unable to interpret plain objects.

Fact 3: What I was calling "TrackJS intercepting (capturing) errors" was actually this addon doing funny stuff. I've looked into [`Ember.RSVP` source](https://github.com/emberjs/ember.js/blob/27862a18b8773e57c52dbc7141b1f92a505f16ff/packages/ember-runtime/lib/ext/rsvp.js#L74) to see how to correctly rethrow errors.

Fact 4: `Ember.RSVP` literally [does](https://github.com/emberjs/ember.js/blob/27862a18b8773e57c52dbc7141b1f92a505f16ff/packages/ember-runtime/lib/ext/rsvp.js#L58) this in its error handling: 

```
if (error && error.name !== 'TransitionAborted') {
```

I'm submitting a PR that addresses all of the mentioned issues (except the first one).

**Comment by lolmaus** [comment]
By the way, why are we handling `Ember.RSVP.on('error')`?

It looks like it should be doing its job correclty: https://github.com/emberjs/ember.js/blob/27862a18b8773e57c52dbc7141b1f92a505f16ff/packages/ember-runtime/lib/ext/rsvp.js#L58-L77

**Comment by jherdman** [comment]
> By the way, why are we handling Ember.RSVP.on('error')?

Legacy. At one point in time (though I can't recall the cut off) you had to intercept both `Ember.onerror` and `Ember.RSVP.on('error')`. I wasn't aware that that had changed.

A major hat tip to you, good sir. That is some serious sleuthing. I'm reviewing everything now, and I'll be testing out your PR shortly.

**Comment by lolmaus** [comment]
I updated my PR. Please close this one and merge #34.

**Pull request closed without merging**
