### PR TITLE
Modernize add-on

### PR DESCRIPTION
**Pull request by bobisjan**
- run `npx ember-cli-update`
- migrate to Octane
- remove implicit injections
- unify `trackjs` naming (configuration, initializer, ...) to match with the `trackjs` package
- use `ember-auto-import` to avoid legacy bundling
- added FastBoot test
- simplify configuration object

### CODE REVIEW

**Comment by bobisjan** [comment]
@jherdman 👋, what do you think about this PR? It’s little bit out of date (dependencies should be bumped to recent versions), hence I can update it or (if merged) send follow up PRs

**Comment by jherdman** [comment]
Hi! Firstly let me apologize for not getting to this PR sooner. This project really isn't on my radar these days, and I ought to see if I can get it moved to the adopted programme. 

Next, let me encourage you to NOT use this addon. It has near zero value in modern Ember as it's trivial to wrap any third party script in a service (or whatever is most appropriate). As the code is MIT licensed you should also feel free to copy anything you want from it. 

Now that that's out of the way, I'll get to this asap and try and cut a release for you. This will likely mark the last release I'll do short of it being managed by the adopted programme.

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
I'm going to merge this under the assumption CI is green. Are you amenable to additional PRs if there's a build failure?

**Comment by bobisjan** [comment]
> Next, let me encourage you to NOT use this addon. It has near zero value in modern Ember as it's trivial to wrap any third party script in a service (or whatever is most appropriate). As the code is MIT licensed you should also feel free to copy anything you want from it.

Sounds reasonable, will take a look 🕵️‍♂️

> I'm going to merge this under the assumption CI is green. Are you amenable to additional PRs if there's a build failure?

I'm going to make CI green 💚

**Pull request merged**
