### PR TITLE
Correctly Handle Ember Errors

### PR DESCRIPTION
**Pull request by jherdman**
TODO
---------

- [x] Beef up acceptance tests
- [x] Try in a production app

### CODE REVIEW

**Comment by lolmaus** [comment]
I'll talk to my team to try it in our production apps ( http://firecracker.me ).

Please mark this branch as protected in your repo's settings (prevents deletion and force-pushing). Alternatively, we can simply copy-paste the initializer into the apps directly rather than depending on the addon.

**Comment by jherdman** [comment]
So far so good. It works great with our production app, precisionnutrition.com

**Comment by jherdman** [comment]
I can verify your difficulties with the acceptance tests. I really want to make sure tests are running before I release this. I'm very confident that it works, but running tests will make me a lot happier :)

**Comment by jherdman** [comment]
Boom! Tests are in place. If this goes green I'm going to merge and release it.

**Comment by lolmaus** [comment]
As I said, error you're intentionally throwing from routes leak into QUnit and fail your tests.

**Comment by jherdman** [comment]
Yeah... :(

**Comment by jherdman** [comment]
@lolmaus I think I just came up with a clever workaround for the testing situation. Let me know what you think.

**Comment by lolmaus** [comment]
Clever indeed! I was thinking about acceptance test and totally missed that it can be tested in a more straightforward way.

PS Are you in Ember Slack Community? Signup page: https://ember-community-slackin.herokuapp.com/

**Comment by lolmaus** [comment]
Thank you! :D

**Pull request merged**
