### PR TITLE
Package TrackJS

### PR DESCRIPTION
**Pull request by jherdman**
Please see commits for details

TODO
--------

- [x] Ensure this works in a live app
- [x] Verify upgrade procedure described in UPGRADE.md
- [x] Add deprecation notice for usage of `trackJs.addon.url`

### CODE REVIEW

**Comment by gzurbach** [comment]
Awesome work @jherdman 
I pretty busy at the moment but I give a try to that version ASAP

**Comment by karellm** [comment]
@jherdman I was looking through the code to do exactly this and was about to make a PR. The changes look great. Any chance to see this merged soon?

Also, I would argue (not that I need it) that it would better for backward compatibility to leave the option to include an url. Some people might prefer to use the CDN to stay up to date. WDYT?

**Comment by karellm** [comment]
@jherdman I forgot to mention that I tested this branch in my app and it works perfectly!

**Comment by jherdman** [comment]
@karellm good point, I'll definitely leave the URL in.

**Pull request merged**
